name: Merge Workflow
on:
  push:
    branches:
      - dev

jobs:
  merge-to-stage:
    runs-on: ubuntu-latest
    steps:
      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Fetch and checkout stage branch
        run: |
          git fetch origin stage
          git checkout -b stage origin/stage

      - name: Merge dev into stage
        run: |
          git merge dev --no-ff --no-edit --allow-unrelated-histories
          git push origin stage

  merge-to-main:
    needs: merge-to-stage
    runs-on: ubuntu-latest
    steps:
      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Fetch and checkout main branch
        run: |
          git fetch origin main
          git checkout -b main origin/main

      - name: Merge stage into main
        run: |
          git merge stage --no-ff --no-edit --allow-unrelated-histories
          git push origin main
